apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: food-delivery/cart-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GIN_MODE
          value: "release"
        - name: MODULE
          value: "cart"
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: db-connection-string
              key: DB_DSN
        - name: FOOD_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FOOD_SERVICE_URL
        - name: RESTAURANT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RESTAURANT_SERVICE_URL
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: uploads
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: food-delivery
spec:
  selector:
    app: cart-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
