apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-new
  labels:
    type: local
    app: minio
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/minio"
